apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  baseImage: leader.telekube.local:5000/prometheus/alertmanager
  nodeSelector:
    beta.kubernetes.io/os: linux
    gravitational.io/k8s-role: master
  replicas: 3
  resources:
    requests:
      memory: 50Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  containers:
    - name: mta
      image: leader.telekube.local:5000/monitoring-mta:1.0.0
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: alertmanager
            operator: In
            values:
              - main
          - key: app
            operator: In
            values:
              - alertmanager
        topologyKey: kubernetes.io/hostname
  tolerations:
  - key: "gravitational.io/runlevel"
    value: system
    operator: Equal
  # allows to run on master nodes
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  version: v0.16.2
